### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by w4lle** [amitshekhariitbhu/Android-Debug-Database#11]
```
      java.lang.NullPointerException: Attempt to get length of null array
      at com.amitshekhar.server.ClientServer.getDBList(ClientServer.java:412)
      at com.amitshekhar.server.ClientServer.handle(ClientServer.java:216)
       at com.amitshekhar.server.ClientServer.run(ClientServer.java:128)
      at java.lang.Thread.run(Thread.java:818)
```

**Comment by amitshekhariitbhu** [comment]
https://github.com/amitshekhariitbhu/Android-Debug-Database/issues/10
