### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Kandr0s** [amitshekhariitbhu/Android-Debug-Database#118]
When starting my Application a huge error log is written:
[Pastebin](https://pastebin.com/HhHSV45v)

After that my Application is crashing with a NullPointerException

`E/ClientServer: Exception.
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
        at com.amitshekhar.server.RequestHandler.openDatabase(RequestHandler.java:182)
        at com.amitshekhar.server.RequestHandler.getTableListResponse(RequestHandler.java:304)
        at com.amitshekhar.server.RequestHandler.handle(RequestHandler.java:113)
        at com.amitshekhar.server.ClientServer.run(ClientServer.java:76)
        at java.lang.Thread.run(Thread.java:762)`

**Comment by EminDemiri** [comment]
I have the same problem

**Comment by ajitdubey-mob-ibtech** [comment]
is there any update?
having same issue

**Comment by hyoungtaikkim** [comment]
having same issue.

Android Studio 3.1.4

phone's OS version : Android 8.0.0

target sdk version : 27

Thanks.

**Comment by Kandr0s** [comment]
So thats it? Just closing?

**Comment by Kandr0s** [comment]
This error has nothing to do with room...
just closing without any form of response is just sad.
At least catch the NullPointerException.
