### ISSUE TITLE
Cannot compile it on Android 4.2.2. Getting this exception

### ISSUE THREAD

**Issue by AhmadAyyaz1993** [amitshekhariitbhu/Android-Debug-Database#121]
java.lang.RuntimeException: Unable to get provider com.amitshekhar.DebugDBInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.amitshekhar.DebugDBInitProvider" on path: DexPathList[[zip file "/data/app/com.ckfc.timekeep-5.apk"],nativeLibraryDirectories=[/data/app-lib/com.ckfc.timekeep-5, /vendor/lib, /system/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:5236)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4828)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4711)
        at android.app.ActivityThread.access$1600(ActivityThread.java:175)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:146)
        at android.app.ActivityThread.main(ActivityThread.java:5602)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.amitshekhar.DebugDBInitProvider" on path: DexPathList[[zip file "/data/app/com.ckfc.timekeep-5.apk"],nativeLibraryDirectories=[/data/app-lib/com.ckfc.timekeep-5, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5221)

**Comment by solomonmetta** [comment]
Did anyone get a solution to this? Getting same exception with Android 4.4

**Comment by solomonmetta** [comment]
> Did anyone get a solution to this? Getting same exception with Android 4.4

In my case it was a multidex issue. 
https://android.jlelse.eu/how-to-configure-multidex-in-an-application-android-f221198707ed
