### ISSUE TITLE
Does not work with android studio 3.2 rc 3

### ISSUE THREAD

**Issue by FloJ12** [amitshekhariitbhu/Android-Debug-Database#134]
java.lang.RuntimeException: Unable to get provider com.amitshekhar.DebugDBInitProvider: android.content.res.Resources$NotFoundException: String resource ID #0x7f0f0002
        at android.app.ActivityThread.installProvider(ActivityThread.java:6242)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5805)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at...

Before the update everything was working flawless!

**Comment by FloJ12** [comment]
I can give you a full log of the error message when I get home, but otherwise unfortunately not... I removed your DebugDB for now and my Project builds again… 
Can you reproduce the error?

**Comment by ysls** [comment]
@FloJ12  Delete the "build" folder both of root and app module, and rebulid project.  it worked for me.
