### ISSUE TITLE
NoSuchMethodError: native_getDbLookaside()

### ISSUE THREAD

**Issue by Guiorgy** [amitshekhariitbhu/Android-Debug-Database#148]
```
Failed to register native method net.sqlcipher.database.SQLiteDatabase.native_getDbLookaside()I in /data/app/base.apk
----- class 'Lnet/sqlcipher/database/SQLiteDatabase;' cl=0x12c70720 -----
objectSize=620 (136 from super)
access=0x8008.0001
super='java.lang.Class<net.sqlcipher.database.SQLiteClosable>' (cl=0x12c70720)
vtable (40 entries, 5 in super):
0: void net.sqlcipher.database.SQLiteDatabase.addSQLiteClosable(net.sqlcipher.database.SQLiteClosable)
1: void net.sqlcipher.database.SQLiteDatabase.addToCompiledQueries(java.lang.String, net.sqlcipher.database.SQLiteCompiledSql)
2: void net.sqlcipher.database.SQLiteDatabase.checkLockHoldTime()
3: void net.sqlcipher.database.SQLiteDatabase.close()
4: void net.sqlcipher.database.SQLiteDatabase.closeClosable()
5: net.sqlcipher.database.SQLiteStatement net.sqlcipher.database.SQLiteDatabase.compileStatement(java.lang.String)
6: boolean net.sqlcipher.database.SQLiteDatabase.containsNull(char[])
7: void net.sqlcipher.database.SQLiteDatabase.dbclose()
8: void net.sqlcipher.database.SQLiteDatabase.dbopen(java.lang.String, int)
9: void net.sqlcipher.database.SQLiteDatabase.deallocCachedSqlStatements()
10: int net.sqlcipher.database.SQLiteDatabase.delete(java.lang.String, java.lang.String, java.lang.String[])
11: void net.sqlcipher.database.SQLiteDatabase.enableSqlProfiling(java.lang.String)
12: void net.sqlcipher.database.SQLiteDatabase.enableSqlTracing(java.lang.String)
13: void net.sqlcipher.database.SQLiteDatabase.execSQL(java.lang.String)
14: void net.sqlcipher.database.SQLiteDatabase.finalize()
15: byte[] net.sqlcipher.database.SQLiteDatabase.getBytes(char[])
16: net.sqlcipher.database.SQLiteCompiledSql net.sqlcipher.database.SQLiteDatabase.getCompiledStatementForSql(java.lang.String)
17: java.lang.String net.sqlcipher.database.SQLiteDatabase.getPath()
18: java.lang.String net.sqlcipher.database.SQLiteDatabase.getTime()
19: int net.sqlcipher.database.SQLiteDatabase.getVersion()
20: long net.sqlcipher.database.SQLiteDatabase.insert(java.lang.String, java.lang.String, android.content.ContentValues)
21: long net.sqlcipher.database.SQLiteDatabase.insertWithOnConflict(java.lang.String, java.lang.String, android.content.ContentValues, int)
22: boolean net.sqlcipher.database.SQLiteDatabase.isOpen()
23: void net.sqlcipher.database.SQLiteDatabase.key(byte[])
24: void net.sqlcipher.database.SQLiteDatabase.keyDatabase(net.sqlcipher.database.SQLiteDatabaseHook, java.lang.Runnable)
25: void net.sqlcipher.database.SQLiteDatabase.key_mutf8(char[])
26: int net.sqlcipher.database.SQLiteDatabase.lastChangeCount()
27: long net.sqlcipher.database.SQLiteDatabase.lastInsertRow()
28: void net.sqlcipher.database.SQLiteDatabase.lock()
29: void net.sqlcipher.database.SQLiteDatabase.native_execSQL(java.lang.String)
30: void net.sqlcipher.database.SQLiteDatabase.onAllReferencesReleased()
31: void net.sqlcipher.database.SQLiteDatabase.onCorruption()
32: void net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(char[], net.sqlcipher.database.SQLiteDatabaseHook)
33: net.sqlcipher.Cursor net.sqlcipher.database.SQLiteDatabase.rawQuery(java.lang.String, java.lang.String[])
34: net.sqlcipher.Cursor net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(net.sqlcipher.database.SQLiteDatabase$CursorFactory, java.lang.String, java.lang.String[], java.lang.String)
35: void net.sqlcipher.database.SQLiteDatabase.rekey(byte[])
36: void net.sqlcipher.database.SQLiteDatabase.removeSQLiteClosable(net.sqlcipher.database.SQLiteClosable)
37: void net.sqlcipher.database.SQLiteDatabase.unlock()
38: int net.sqlcipher.database.SQLiteDatabase.update(java.lang.String, android.content.ContentValues, java.lang.String, java.lang.String[])
39: int net.sqlcipher.database.SQLiteDatabase.updateWithOnConflict(java.lang.String, android.content.ContentValues, java.lang.String, java.lang.String[], int)
2019-02-21 16:32:29.066 16294-16369/? E/art:   direct methods (11 entries):
0: void net.sqlcipher.database.SQLiteDatabase.<clinit>()
1: void net.sqlcipher.database.SQLiteDatabase.<init>(java.lang.String, net.sqlcipher.database.SQLiteDatabase$CursorFactory, int, net.sqlcipher.DatabaseErrorHandler)
2: void net.sqlcipher.database.SQLiteDatabase.access$000(net.sqlcipher.database.SQLiteDatabase, byte[])
3: void net.sqlcipher.database.SQLiteDatabase.access$100(net.sqlcipher.database.SQLiteDatabase, char[])
4: void net.sqlcipher.database.SQLiteDatabase.loadLibs(android.content.Context)
5: void net.sqlcipher.database.SQLiteDatabase.loadLibs(android.content.Context, java.io.File)
6: void net.sqlcipher.database.SQLiteDatabase.loadLibs(android.content.Context, java.io.File, net.sqlcipher.database.SQLiteDatabase$LibraryLoader)
7: net.sqlcipher.database.SQLiteDatabase net.sqlcipher.database.SQLiteDatabase.openDatabase(java.lang.String, java.lang.String, net.sqlcipher.database.SQLiteDatabase$CursorFactory, int, net.sqlcipher.database.SQLiteDatabaseHook)
8: net.sqlcipher.database.SQLiteDatabase net.sqlcipher.database.SQLiteDatabase.openDatabase(java.lang.String, java.lang.String, net.sqlcipher.database.SQLiteDatabase$CursorFactory, int, net.sqlcipher.database.SQLiteDatabaseHook, net.sqlcipher.DatabaseErrorHandler)
9: net.sqlcipher.database.SQLiteDatabase net.sqlcipher.database.SQLiteDatabase.openDatabase(java.lang.String, char[], net.sqlcipher.database.SQLiteDatabase$CursorFactory, int, net.sqlcipher.database.SQLiteDatabaseHook, net.sqlcipher.DatabaseErrorHandler)
10: net.sqlcipher.database.SQLiteDatabase net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(java.lang.String, java.lang.String, net.sqlcipher.database.SQLiteDatabase$CursorFactory)
static fields (2 entries):
0: java.lang.String[] net.sqlcipher.database.SQLiteDatabase.CONFLICT_VALUES
1: java.util.WeakHashMap net.sqlcipher.database.SQLiteDatabase.sActiveDatabases
instance fields (20 entries):
0: int net.sqlcipher.database.SQLiteDatabase.mCacheFullWarnings
1: java.util.Map net.sqlcipher.database.SQLiteDatabase.mCompiledQueries
2: net.sqlcipher.DatabaseErrorHandler net.sqlcipher.database.SQLiteDatabase.mErrorHandler
3: net.sqlcipher.database.SQLiteDatabase$CursorFactory net.sqlcipher.database.SQLiteDatabase.mFactory
4: int net.sqlcipher.database.SQLiteDatabase.mFlags
5: long net.sqlcipher.database.SQLiteDatabase.mLastLockMessageTime
6: java.util.concurrent.locks.ReentrantLock net.sqlcipher.database.SQLiteDatabase.mLock
7: long net.sqlcipher.database.SQLiteDatabase.mLockAcquiredThreadTime
8: long net.sqlcipher.database.SQLiteDatabase.mLockAcquiredWallTime
9: boolean net.sqlcipher.database.SQLiteDatabase.mLockingEnabled
10: int net.sqlcipher.database.SQLiteDatabase.mMaxSqlCacheSize
11: long net.sqlcipher.database.SQLiteDatabase.mNativeHandle
12: int net.sqlcipher.database.SQLiteDatabase.mNumCacheHits
13: int net.sqlcipher.database.SQLiteDatabase.mNumCacheMisses
14: java.lang.String net.sqlcipher.database.SQLiteDatabase.mPath
15: java.util.WeakHashMap net.sqlcipher.database.SQLiteDatabase.mPrograms
6: int net.sqlcipher.database.SQLiteDatabase.mSlowQueryThreshold
17: java.lang.Throwable net.sqlcipher.database.SQLiteDatabase.mStackTrace
18: java.lang.String net.sqlcipher.database.SQLiteDatabase.mTimeClosed
19: java.lang.String net.sqlcipher.database.SQLiteDatabase.mTimeOpened
...
art/runtime/java_vm_ext.cc:410]   at java.lang.Runtime.nativeLoad(Native method)
art/runtime/java_vm_ext.cc:410]   at java.lang.Runtime.doLoad(Runtime.java:435)
art/runtime/java_vm_ext.cc:410]   - locked <0x0141a639> (a java.lang.Runtime)
art/runtime/java_vm_ext.cc:410]   at java.lang.Runtime.loadLibrary(Runtime.java:370)
art/runtime/java_vm_ext.cc:410]   at java.lang.System.loadLibrary(System.java:1076)
art/runtime/java_vm_ext.cc:410]   at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries(SQLiteDatabase.java:213)
art/runtime/java_vm_ext.cc:410]   at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:230)
art/runtime/java_vm_ext.cc:410]   - locked <0x04a268e7> (a java.lang.Class<net.sqlcipher.database.SQLiteDatabase>)
art/runtime/java_vm_ext.cc:410]   at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:209)
art/runtime/java_vm_ext.cc:410]   - locked <0x04a268e7> (a java.lang.Class<net.sqlcipher.database.SQLiteDatabase>)
art/runtime/java_vm_ext.cc:410]   at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:202)
art/runtime/java_vm_ext.cc:410]   - locked <0x04a268e7> (a java.lang.Class<net.sqlcipher.database.SQLiteDatabase>)
art/runtime/java_vm_ext.cc:410]   at com.amitshekhar.server.RequestHandler.openDatabase(RequestHandler.java:184)
art/runtime/java_vm_ext.cc:410]   at com.amitshekhar.server.RequestHandler.getTableListResponse(RequestHandler.java:304)
art/runtime/java_vm_ext.cc:410]   at com.amitshekhar.server.RequestHandler.handle(RequestHandler.java:113)
art/runtime/java_vm_ext.cc:410]   at com.amitshekhar.server.ClientServer.run(ClientServer.java:76)
art/runtime/java_vm_ext.cc:410]   at java.lang.Thread.run(Thread.java:818)
...
art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: JNI FindClass called with pending exception java.lang.NoSuchMethodError: no static or non-static method "Lnet/sqlcipher/database/SQLiteDatabase;.native_getDbLookaside()I"
art/runtime/java_vm_ext.cc:410]   at java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.String) (Runtime.java:-2)
art/runtime/java_vm_ext.cc:410]   at java.lang.String java.lang.Runtime.doLoad(java.lang.String, java.lang.ClassLoader) (Runtime.java:435)
art/runtime/java_vm_ext.cc:410]   at void java.lang.Runtime.loadLibrary(java.lang.String, java.lang.ClassLoader) (Runtime.java:370)
art/runtime/java_vm_ext.cc:410]   at void java.lang.System.loadLibrary(java.lang.String) (System.java:1076)
art/runtime/java_vm_ext.cc:410]   at void net.sqlcipher.database.SQLiteDatabase$1.loadLibraries(java.lang.String[]) (SQLiteDatabase.java:213)
art/runtime/java_vm_ext.cc:410]   at void net.sqlcipher.database.SQLiteDatabase.loadLibs(android.content.Context, java.io.File, net.sqlcipher.database.SQLiteDatabase$LibraryLoader) (SQLiteDatabase.java:230)
art/runtime/java_vm_ext.cc:410]   at void net.sqlcipher.database.SQLiteDatabase.loadLibs(android.content.Context, java.io.File) (SQLiteDatabase.java:209)
art/runtime/java_vm_ext.cc:410]   at void net.sqlcipher.database.SQLiteDatabase.loadLibs(android.content.Context) (SQLiteDatabase.java:202)
art/runtime/java_vm_ext.cc:410]   at void com.amitshekhar.server.RequestHandler.openDatabase(java.lang.String) (RequestHandler.java:184)
art/runtime/java_vm_ext.cc:410]   at java.lang.String com.amitshekhar.server.RequestHandler.getTableListResponse(java.lang.String) (RequestHandler.java:304)
art/runtime/java_vm_ext.cc:410]   at void com.amitshekhar.server.RequestHandler.handle(java.net.Socket) (RequestHandler.java:113)
art/runtime/java_vm_ext.cc:410]   at void com.amitshekhar.server.ClientServer.run() (ClientServer.java:76)
art/runtime/java_vm_ext.cc:410]   at void java.lang.Thread.run() (Thread.java:818)
```

**Comment by Guiorgy** [comment]
After moving to 1.0.5 seems to be working so far.
