### ISSUE TITLE
'java.lang.Object android.util.Pair.first' on a null object reference

### ISSUE THREAD

**Issue by prapkengr** [amitshekhariitbhu/Android-Debug-Database#162]

**Comment by prapkengr** [comment]
When I open the db from browser, error is 

E/ClientServer: Exception.
    java.lang.NullPointerException: Attempt to read from field 'java.lang.Object android.util.Pair.first' on a null object reference
        at com.amitshekhar.server.RequestHandler.openDatabase(RequestHandler.java:182)
        at com.amitshekhar.server.RequestHandler.getTableListResponse(RequestHandler.java:304)
        at com.amitshekhar.server.RequestHandler.handle(RequestHandler.java:113)
        at com.amitshekhar.server.ClientServer.run(ClientServer.java:76)
        at java.lang.Thread.run(Thread.java:818)


Environment:
debugImplementation 'com.amitshekhar.android:debug-db:1.0.6'
        minSdkVersion 23
        targetSdkVersion 28

Source project:
https://github.com/srinurp/workmanager
with version and all updated to make it work.

**Comment by GinRyan** [comment]
I replayed this review. I guess maybe it's a SQLite bug. While database name contains a '#' symbol,  you run a query on this sick database , the error will be replayed.

**Comment by mohsencadir1** [comment]
I had this problem too, any solution?
