### ISSUE TITLE
[1.0.6] Failed resolution of: Lcom/amitshekhar/sqlite/DBFactory

### ISSUE THREAD

**Issue by osvalr** [amitshekhariitbhu/Android-Debug-Database#189]
I just had this error at runtime

```
--------- beginning of crash
05-28 16:24:27.239 23059 23059 E AndroidRuntime: FATAL EXCEPTION: main
05-28 16:24:27.239 23059 23059 E AndroidRuntime: Process: com.my-package, PID: 23059
05-28 16:24:27.239 23059 23059 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/amitshekhar/sqlite/DBFactory;
05-28 16:24:27.239 23059 23059 E AndroidRuntime:        at java.lang.Class.newInstance(Native Method)
05-28 16:24:27.239 23059 23059 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:5841)
05-28 16:24:27.239 23059 23059 E AndroidRuntime:        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5445)
05-28 16:24:27.239 23059 23059 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5384)
05-28 16:24:27.239 23059 23059 E AndroidRuntime:        at android.app.ActivityThread.-wrap2(ActivityThread.java)
05-28 16:24:27.239 23059 23059 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
05-28 16:24:27.239 23059 23059 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
05-28 16:24:27.239 23059 23059 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
05-28 16:24:27.239 23059 23059 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6119)
05-28 16:24:27.239 23059 23059 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-28 16:24:27.239 23059 23059 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
05-28 16:24:27.239 23059 23059 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
05-28 16:24:27.239 23059 23059 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.amitshekhar.sqlite.DBFactory" on path: DexPathList[[zip file "/data/app/com.my-package-1/base.apk"],nativeLibraryDirectories=[/data/app/com.my-package-1/lib/x86, /system/lib, /vendor/lib]]
05-28 16:24:27.239 23059 23059 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-28 16:24:27.239 23059 23059 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
05-28 16:24:27.239 23059 23059 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05-28 16:24:27.239 23059 23059 E AndroidRuntime:        ... 12 more
05-28 16:24:27.240  1744  2478 W ActivityManager:   Force finishing activity com.my-package/com.my-package.ui.SplashActivity
05-28 16:24:27.302  1744 11470 I OpenGLRenderer: Initialized EGL, version 1.4
05-28 16:24:27.302  1744 11470 D OpenGLRenderer: Swap behavior 1
```

And I found out I because of this error I had to enable transitive dependencies so my `app/build.gradle` looks like the following:
```
dependencies {
...
    debugImplementation('com.amitshekhar.android:debug-db:1.0.6@aar') {
        transitive = true
    }
}
...
```

**Comment by osvalr** [comment]
@amitshekhariitbhu thank for this lib btw
