### ISSUE TITLE
NetworkUtils.java line 38

### ISSUE THREAD

**Issue by Drjacky** [amitshekhariitbhu/Android-Debug-Database#214]
```groovy
Fatal Exception: java.lang.RuntimeException: Unable to get provider com.amitshekhar.debug.DebugDBInitProvider: java.lang.SecurityException: WifiService: Neither user 12175 nor current process has android.permission.ACCESS_WIFI_STATE.
       at android.app.ActivityThread.installProvider(ActivityThread.java:6770)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:6312)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6227)
       at android.app.ActivityThread.access$1200(ActivityThread.java:238)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1787)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

Caused by java.lang.SecurityException: WifiService: Neither user 12175 nor current process has android.permission.ACCESS_WIFI_STATE.
       at android.os.Parcel.createException(Parcel.java:1966)
       at android.os.Parcel.readException(Parcel.java:1934)
       at android.os.Parcel.readException(Parcel.java:1884)
       at android.net.wifi.IWifiManager$Stub$Proxy.getConnectionInfo(IWifiManager.java:1786)
       at android.net.wifi.WifiManager.getConnectionInfo(WifiManager.java:2057)
       at com.amitshekhar.utils.NetworkUtils.getAddressLog(NetworkUtils.java:38)
       at com.amitshekhar.DebugDB.initialize(DebugDB.java:62)
       at com.amitshekhar.debug.DebugDBInitProvider.onCreate(DebugDBInitProvider.java:44)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:1940)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:1915)
       at com.amitshekhar.debug.DebugDBInitProvider.attachInfo(DebugDBInitProvider.java:83)
       at android.app.ActivityThread.installProvider(ActivityThread.java:6765)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:6312)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6227)
       at android.app.ActivityThread.access$1200(ActivityThread.java:238)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1787)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

Caused by android.os.RemoteException: Remote stack trace:
        at android.app.ContextImpl.enforce(ContextImpl.java:1924)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1952)
        at com.android.server.wifi.WifiServiceImpl.enforceAccessPermission(WifiServiceImpl.java:1580)
        at com.android.server.wifi.WifiServiceImpl.getConnectionInfo(WifiServiceImpl.java:3646)
        at android.net.wifi.IWifiManager$Stub.onTransact(IWifiManager.java:341)
```

**Device**
Brand:samsung
Model:Galaxy S8
Version: Android 9

**Comment by alwoalwo42gmailcom** [comment]
https://duckduckgo.com/?q=http%3A%2F%2F0.0.0.0%3A8080&ko=-1&atb=v273-1&t=ddg_android&ia=qa
