### ISSUE TITLE
App crash when I open url in browser

### ISSUE THREAD

**Issue by sanjay-kakadiya** [amitshekhariitbhu/Android-Debug-Database#31]
I added dependency `debugCompile 'com.amitshekhar.android:debug-db:0.4.0'` and run android app it's running well. but when I open http://192.168.1.19:8080/ in browser app crash with below log.
192.168.1.19 is device ip.
Device: Moto G Turbo running on Android 6.0.1

```
FATAL EXCEPTION: Thread-21799
Process: com.xxxxx, PID: 5228
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.FileDescriptor.setInt$(int)' on a null object reference
at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:93)
at java.net.ServerSocket.implAccept(ServerSocket.java:217)
at java.net.ServerSocket.accept(ServerSocket.java:141)
at com.amitshekhar.server.ClientServer.run(ClientServer.java:126)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by amitshekhariitbhu** [comment]
I will check the issue and update you soon on this.

**Comment by amitshekhariitbhu** [comment]
handled

**Comment by sanjay-kakadiya** [comment]
Thanks, It's worked now. Thanks for such an awesome tool.
