### ISSUE TITLE
Library not working if table name is a reserved keyword.

### ISSUE THREAD

**Issue by gogeta95** [amitshekhariitbhu/Android-Debug-Database#47]
Made a table with name "transaction" in my app, and library crashes when i request that table.

Stack trace:

```
03-29 10:01:47.594 30095-30114/in.shipsy.riderapp.firstmile E/SQLiteLog: (1) near "transaction": syntax error
03-29 10:01:47.594 30095-30114/in.shipsy.riderapp.firstmile W/System.err: android.database.sqlite.SQLiteException: near "transaction": syntax error (code 1): , while compiling: SELECT * FROM transaction
03-29 10:01:47.594 30095-30114/in.shipsy.riderapp.firstmile W/System.err:     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
03-29 10:01:47.594 30095-30114/in.shipsy.riderapp.firstmile W/System.err:     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
03-29 10:01:47.594 30095-30114/in.shipsy.riderapp.firstmile W/System.err:     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
03-29 10:01:47.594 30095-30114/in.shipsy.riderapp.firstmile W/System.err:     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
03-29 10:01:47.594 30095-30114/in.shipsy.riderapp.firstmile W/System.err:     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
03-29 10:01:47.594 30095-30114/in.shipsy.riderapp.firstmile W/System.err:     at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
03-29 10:01:47.594 30095-30114/in.shipsy.riderapp.firstmile W/System.err:     at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
03-29 10:01:47.594 30095-30114/in.shipsy.riderapp.firstmile W/System.err:     at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
03-29 10:01:47.594 30095-30114/in.shipsy.riderapp.firstmile W/System.err:     at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1253)
03-29 10:01:47.594 30095-30114/in.shipsy.riderapp.firstmile W/System.err:     at com.amitshekhar.utils.DatabaseHelper.getTableData(DatabaseHelper.java:80)
03-29 10:01:47.594 30095-30114/in.shipsy.riderapp.firstmile W/System.err:     at com.amitshekhar.server.RequestHandler.getAllDataFromTheTableResponse(RequestHandler.java:197)
03-29 10:01:47.594 30095-30114/in.shipsy.riderapp.firstmile W/System.err:     at com.amitshekhar.server.RequestHandler.handle(RequestHandler.java:102)
03-29 10:01:47.594 30095-30114/in.shipsy.riderapp.firstmile W/System.err:     at com.amitshekhar.server.ClientServer.run(ClientServer.java:75)
03-29 10:01:47.594 30095-30114/in.shipsy.riderapp.firstmile W/System.err:     at java.lang.Thread.run(Thread.java:841)
```

I'd like to fix this bug. Thanks.

**Comment by amitshekhariitbhu** [comment]
sure sure

**Comment by amitshekhariitbhu** [comment]
Released new version with this fix
