### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by carvaldo** [amitshekhariitbhu/Android-Debug-Database#74]
My application has a pre-populated DB with just over 30 thousand tuples, while running the application is giving the following stack trace:
`FATAL EXCEPTION: Thread-3
                                                                       Process: br.com.crvlagoa.paint, PID: 23359
                                                                       java.lang.OutOfMemoryError: Failed to allocate a 150994952 byte allocation with 16777216 free bytes and 60MB until OOM
                                                                           at java.util.Arrays.copyOf(Arrays.java:3352)
                                                                           at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
                                                                           at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
                                                                           at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:417)
                                                                           at java.lang.StringBuffer.append(StringBuffer.java:237)
                                                                           at java.io.StringWriter.write(StringWriter.java:112)
                                                                           at com.google.gson.stream.JsonWriter.string(JsonWriter.java:591)
                                                                           at com.google.gson.stream.JsonWriter.writeDeferredName(JsonWriter.java:402)
                                                                           at com.google.gson.stream.JsonWriter.value(JsonWriter.java:417)
                                                                           at com.google.gson.internal.bind.TypeAdapters$16.write(TypeAdapters.java:405)
                                                                           at com.google.gson.internal.bind.TypeAdapters$16.write(TypeAdapters.java:389)
                                                                           at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
                                                                           at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
                                                                           at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
                                                                           at com.google.gson.internal.bind.ObjectTypeAdapter.write(ObjectTypeAdapter.java:107)
                                                                           at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
                                                                           at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
                                                                           at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
                                                                           at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
                                                                           at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
                                                                           at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
                                                                           at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
                                                                           at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
                                                                           at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
                                                                           at com.google.gson.Gson.toJson(Gson.java:669)
                                                                           at com.google.gson.Gson.toJson(Gson.java:648)
                                                                           at com.google.gson.Gson.toJson(Gson.java:603)
                                                                           at com.google.gson.Gson.toJson(Gson.java:583)
                                                                           at com.amitshekhar.server.RequestHandler.getAllDataFromTheTableResponse(RequestHandler.java:214)
                                                                           at com.amitshekhar.server.RequestHandler.handle(RequestHandler.java:103)
                                                                           at com.amitshekhar.server.ClientServer.run(ClientServer.java:78)
                                                                           at java.lang.Thread.run(Thread.java:761)`

**Comment by amitshekhariitbhu** [comment]
Ok, we can solve it by implementing pagination feature in the library. We will try to include the pagination in the new version.

**Comment by PeterXiaosa** [comment]
> Ok, we can solve it by implementing pagination feature in the library. We will try to include the pagination in the new version.

we get the error still now ......
